---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bluegalaxy
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/cosmic-atomic
image-version: 42 

modules:
  - from-file: common/foundation.yml
  - from-file: common/default-flatpaks.yml
  - from-file: common/final-modules.yml
